sudo: false
dist: trusty

addons:
  chrome: stable
  apt:
    update: true

language: ruby

rvm:
  - 2.2.3

cache:
  bundler: true

services:
  - mysql

before_install:
 - gem update --system

before_script:
  - ./travis-prep.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # give xvfb some time to start
  - "while [ ! -e /tmp/.X11-unix/X99 ]; do sleep 1; done"
  - "echo TMPDIR: $(env | grep TMPDIR)"
