sudo: false
dist: xenial

serices:
  - mysql
  - xvfb

notifications:
  email:
    recipients:
      - mark.reyes@ucop.edu
      - terrence.brady@ucop.edu
      - eric.lopatin@ucop.edu

addons:
  chrome: stable
  apt:
    update: true

language: ruby

rvm:
  - 2.7.0

cache:
  bundler: true

before_install:
  # start mysql
  - sudo systemctl start mysql
  # wait for mysql service to respond
  - which mysql && until mysql -u root -e "show status" &>/dev/null; do sleep 1; done
  # set up MySQL 5.7
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root
  - sudo service mysql restart
  # update gems
  - gem update --system
  - gem install bundler:2.1.4

before_script:
  # run travis-prep.sh
  - ./travis-prep.sh
  # set up xvfb
  - "export DISPLAY=:99.0"
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
