sudo: false
dist: trusty

env:
  global:
    - TMPDIR=/tmp

addons:
  chrome: stable

language: ruby
cache: bundler

rvm:
  - 2.2.3

services:
  - mysql

before_install:
 - gem update --system
 - ./travis-prep.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # give xvfb some time to start
  - "while [ ! -e /tmp/.X11-unix/X99 ]; do sleep 1; done"
