version: 0.2

# Pre-requisites
# - Create CodeBuild project
#   - Provide minimal github credentials to access public repo
# test

phases:
  pre_build:
    on-failure: ABORT
    commands:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_REGISTRY}

    - COMMIT=`git rev-parse --short HEAD`
    - BRANCH=`git symbolic-ref -q --short HEAD || git name-rev $(git rev-parse --short HEAD) | cut -d' ' -f2 || echo ''`
    - TAG=`git describe --tags --exact-match 2> /dev/null || echo ''`
    - BRANCHTAG=`git describe --tags --exact-match 2> /dev/null || git symbolic-ref -q --short HEAD || git name-rev $(git rev-parse --short HEAD) | cut -d' ' -f2 || git rev-parse --short HEAD`
    - DOCKTAG=$BRANCHTAG
    - echo "Branchtag ${BRANCHTAG}"

  build:
    on-failure: ABORT
    commands:
    # disable the following to see if build speed improves
    - rbenv versions
    #- bundle install
    #- bundle exec rubocop
      
    - |
      if [[ "${BRANCHTAG}" == "main" ]]
      then
        DOCKTAG='dev'
      fi

    - |
      docker build --push --quiet \
        --build-arg ECR_REGISTRY=${ECR_REGISTRY} \
        -t ${ECR_REGISTRY}/mrt-dashboard:${DOCKTAG} .
    - aws s3 cp swagger.html s3://${S3CFBUCKET}/api/mrt-dashboard/index.html
    - aws s3 cp swagger.yml s3://${S3CFBUCKET}/api/mrt-dashboard/
    - aws cloudfront create-invalidation --distribution-id ${CFDISTRIBUTIONID} --paths /api/mrt-dashboard/ --region us-east-1
