source 'http://rubygems.org'
gem 'rails', '3.0.1'
gem "exception_notification", :git => "git://github.com/rails/exception_notification.git"
gem "json"
gem "net-ldap", "0.1.2", :git=>"git://github.com/RoryO/ruby-net-ldap.git"
gem "nokogiri"
gem "rdf"
gem "rdf-raptor"
gem "rest-client"
gem "ruby-debug"
gem "sqlite3-ruby", :require => "sqlite3"
gem "unicorn"
gem "will_paginate", "~> 3.0.pre2"
gem "sendfile", "1.0.0"
gem "rack-cache"
