default: &default
  host: 127.0.0.1
  adapter: mysql2
  database: mrt_dashboard_test
  username: root
  password: root-password
  encoding: utf8   # schema won't load if it's utf8mb4

development:
  <<: *default

test:
  <<: *default
