default: &default
  credentials: "{!SSM: ui/atom-credential}"

development:
  <<: *default

stage:
  <<: *default

production:
  <<: *default

test:
  credentials: merritt:1212555

docker:
  credentials: pretend-credentials
