default: &default
  host: localhost
  adapter: mysql2
  database: mrt_dashboard_test
  username: travis
  encoding: utf8   # schema won't load if it's utf8mb4

stage:
  adapter: mysql2
  encoding: utf8
  host: {!SSM: inv/db-host}
  database: {!SSM: inv/db-name}
  pool: 5
  port: 3360
  username: {!SSM: inv/readwrite/db-user}
  password: {!SSM: inv/readwrite/db-password}

production:
  adapter: mysql2
  encoding: utf8
  host: {!SSM: inv/db-host}
  database: {!SSM: inv/db-name}
  pool: 5
  port: 3360
  username: {!SSM: inv/readwrite/db-user}
  password: {!SSM: inv/readwrite/db-password}

test:
  <<: *default
