# Tests shouldn't actually talk to LDAP
test: &test
  user: "{!ENV: USER}"
  rb: "{!ENV: SSM_ROOT_PATH}"
  host: "{!SSM: inv/db-host !DEFAULT: ZZZ}"
  foo: bar

stage:
  <<: *test

development:
  <<: *test
