name: Rails Rspec Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
    - uses: actions/checkout@v2

    # Extract the Ruby version from the Gemfile.lock
    - name: 'Determine Ruby Version'
      run: echo ::set-env name=RUBY_VERSION::$(echo `cat ./Gemfile.lock | grep -A 1 'RUBY VERSION' | grep 'ruby' | grep -oE '[0-9]\.[0-9]'`)

    - name: Set up Ruby using version defined in Gemfile.lock
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}

    # Install the necessary MySQL dev packages
    - name: 'Install Mysql Packages'
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client libmysqlclient-dev

    - name: 'Install Bundler'
      run: gem install bundler

    - name: 'Setup Test DB'
      run: bundle exec rake db:setup

    - name: 'Configure Application'
      run: ./travis-prep.sh
      
    - name: Build and test with Rake
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake
